### ISSUE TITLE
Staking function didn't work for e4c contract.

### ISSUE THREAD

**Issue by lychees** [abridged/collabland-staking-contracts#22]
<img width="599" alt="af009dd7ef7b7b1c589f3b32d9a9675" src="https://user-images.githubusercontent.com/2507027/196572045-5a4e595a-17e0-4de9-a3a2-1c28440bd4a4.png">

We have test this morning, and it seems that it didn't work as intended. :(
https://etherscan.io/address/0xCf92d7137ed71b20fCE216bA2eE26c2b1ff4b2c2

**Comment by raymondfeng** [comment]
Pushing to prod. You'll need to add TGRs with the staking contract using https://cc.collab.land.

**Comment by imgrayed** [comment]
Thanks! The changes work now!
