### ISSUE TITLE
SuperVerse staking Contract

### ISSUE THREAD

**Issue by blascokoa** [abridged/collabland-staking-contracts#225]
### Discussed in https://github.com/abridged/collabland-staking-contracts/discussions/224

<div type='discussions-op-text'>

<sup>Originally posted by **blascokoa** April 25, 2024</sup>
Good afternoon guys!

Got an staking contract that can return different values, one is the amount of staked tokens and the other is the staking power, that is based also in the number of NFTs staked into the contract, as each NFT got an equivalent in tokens staked.

Both has been implemented in this repository with the classnames: 
- `SuperverseStakingContractAdapter`
- `SuperverseStakingPowerContractAdapter`

But on collabland I can only see one contract, how do I select one of another for the TGR? 
Or maybe I don't need because it will return under the hood the highest of the 2 values returned?

If you want to take a look to the code, the file is called `superverse-staking.adapter.ts`

Thanks!</div>

**Comment by raymondfeng** [comment]
1. SuperverseStakingPowerContractAdapter was missing `@injectable()`
2. It should use the same adapter for two different assets 

See https://github.com/abridged/collabland-staking-contracts/commit/b55e964b3f516d66ed44a417b6afbdfb531bdff8
